### ISSUE TITLE
Repair travis.ci build

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-reactjs#3]
I've don't change anything into the client directory but the travis.ci failed:
https://travis-ci.org/spring-petclinic/spring-petclinic-reactjs

Some logs:
```
> spring-petclinic-reactjs@0.0.1 build:prod /home/travis/build/spring-petclinic/spring-petclinic-reactjs/client
> rimraf ./public/dist && NODE_ENV=production webpack --config webpack.config.prod.js
ts-loader: Using typescript@2.1.4 and /home/travis/build/spring-petclinic/spring-petclinic-reactjs/client/tsconfig.json
/home/travis/build/spring-petclinic/spring-petclinic-reactjs/client/node_modules/webpack-core/lib/NormalModuleMixin.js:163
			if(isError) throw e;
			            ^
Error: Debug Failure. False expression: 
    at Object.assert (/home/travis/build/spring-petclinic/spring-petclinic-
...
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
```

Compare to the previous successfully build https://travis-ci.org/spring-petclinic/spring-petclinic-reactjs/builds/181606878 I've noticed webpack have been updated : webpack@1.13.3 --> webpack@1.14.0

**Comment by nilshartmann** [comment]
Same reason as #2: current version does not work with TypeScript 2.1. I've modified the package.json accordingly.
