### ISSUE TITLE
Some validation issues

### ISSUE THREAD

**Issue by pinkanpaula** [spring-petclinic/spring-petclinic-reactjs#8]
Below are the list of issues and fixes done in my local dev:

1. Validation should check for valid string values for first name and last name when adding an Owner, fixed this by adding @Pattern(regexp = "[a-z-A-Z]*", message = "First name has invalid characters")

2. Validation should check for null value from date input when adding a Pet, fixed this by adding @NotNull
3. Validation should set a max range for a string with min range, fixed this by adding the max value in @Size(min = 2, max = 14 )

**Comment by nilshartmann** [comment]
Fixed in #9 and #10 

Thanks for your contribution!!
